name: Update

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v4

      - name: Update
        id: update
        run: ./scripts/update.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        if: ${{ steps.update.outputs.updated == 'true' }}
        with:
          title: ${{ steps.update.outputs.pr_title }}
          body: ${{ steps.update.outputs.pr_body }}
          author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          commit-message: ${{ steps.update.outputs.pr_title }}
          branch: update-firefish
          reviewers: ryanccn
