name: Update

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update
        id: update
        run: ./update.sh

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: "feat: update firefish to ${{ steps.update.outputs.rev }}"
          body: ${{ steps.update.outputs.pr-body }}
          commit-message: "feat: update firefish to ${{ steps.update.outputs.rev }}"
          reviewers: ryanccn
